-- Hand-written to add columns via ALTER TABLE ADD COLUMN, preserving existing triggers and
-- expression indexes. The drizzle-kit auto-generated body was discarded because, for tables
-- with expression indexes (unidades/locatarios), it rebuilt the whole table (dropping the
-- audit/immutability triggers) and emitted invalid expression-index SQL. The journal entry and
-- 0005 snapshot from drizzle-kit are kept: they represent the schema.ts state for future diffs.
ALTER TABLE `unidades` ADD COLUMN `codigo_comercial` text(40) CONSTRAINT "unidades_codigo_comercial_text" CHECK(`codigo_comercial` IS NULL OR (typeof(`codigo_comercial`)='text' AND length(trim(`codigo_comercial`))>0)) CONSTRAINT "unidades_codigo_comercial_length" CHECK(`codigo_comercial` IS NULL OR length(`codigo_comercial`)<=40);--> statement-breakpoint
ALTER TABLE `unidades` ADD COLUMN `bloco` text(120) CONSTRAINT "unidades_bloco_text" CHECK(`bloco` IS NULL OR (typeof(`bloco`)='text' AND length(trim(`bloco`))>0)) CONSTRAINT "unidades_bloco_length" CHECK(`bloco` IS NULL OR length(`bloco`)<=120);--> statement-breakpoint
ALTER TABLE `unidades` ADD COLUMN `andar` text(60) CONSTRAINT "unidades_andar_text" CHECK(`andar` IS NULL OR (typeof(`andar`)='text' AND length(trim(`andar`))>0)) CONSTRAINT "unidades_andar_length" CHECK(`andar` IS NULL OR length(`andar`)<=60);--> statement-breakpoint
ALTER TABLE `unidades` ADD COLUMN `area_total` integer CONSTRAINT "unidades_area_total_integer" CHECK(`area_total` IS NULL OR typeof(`area_total`)='integer') CONSTRAINT "unidades_area_total_range" CHECK(`area_total` IS NULL OR `area_total` BETWEEN 0 AND 999999999999);--> statement-breakpoint
ALTER TABLE `unidades` ADD COLUMN `inscricao_municipal` text(80) CONSTRAINT "unidades_inscricao_municipal_text" CHECK(`inscricao_municipal` IS NULL OR (typeof(`inscricao_municipal`)='text' AND length(trim(`inscricao_municipal`))>0)) CONSTRAINT "unidades_inscricao_municipal_length" CHECK(`inscricao_municipal` IS NULL OR length(`inscricao_municipal`)<=80);--> statement-breakpoint
ALTER TABLE `locatarios` ADD COLUMN `canal_preferido` text(40) CONSTRAINT "locatarios_canal_preferido_text" CHECK(`canal_preferido` IS NULL OR (typeof(`canal_preferido`)='text' AND length(trim(`canal_preferido`))>0)) CONSTRAINT "locatarios_canal_preferido_length" CHECK(`canal_preferido` IS NULL OR length(`canal_preferido`)<=40);--> statement-breakpoint
ALTER TABLE `locatarios` ADD COLUMN `endereco_cobranca` text(500) CONSTRAINT "locatarios_endereco_cobranca_text" CHECK(`endereco_cobranca` IS NULL OR (typeof(`endereco_cobranca`)='text' AND length(trim(`endereco_cobranca`))>0)) CONSTRAINT "locatarios_endereco_cobranca_length" CHECK(`endereco_cobranca` IS NULL OR length(`endereco_cobranca`)<=500);--> statement-breakpoint
ALTER TABLE `locatarios` ADD COLUMN `inscricao_municipal` text(80) CONSTRAINT "locatarios_inscricao_municipal_text" CHECK(`inscricao_municipal` IS NULL OR (typeof(`inscricao_municipal`)='text' AND length(trim(`inscricao_municipal`))>0)) CONSTRAINT "locatarios_inscricao_municipal_length" CHECK(`inscricao_municipal` IS NULL OR length(`inscricao_municipal`)<=80);
