-- Hand-written ALTER TABLE ADD COLUMN (drizzle-kit rebuilt the whole `contratos` table because of its
-- table-level CHECKs, which would drop the audit/immutability triggers). Journal + 0006 snapshot kept.
-- These columns preserve the contract form fields; their business use (charge generation, penalties,
-- reajuste application, lifecycle) remains deferred to D04/D05/D06.
ALTER TABLE `contratos` ADD COLUMN `finalidade` text(40) CONSTRAINT "contratos_finalidade_text" CHECK(`finalidade` IS NULL OR (typeof(`finalidade`)='text' AND length(trim(`finalidade`))>0)) CONSTRAINT "contratos_finalidade_length" CHECK(`finalidade` IS NULL OR length(`finalidade`)<=40);--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `data_ocupacao` text(10) CONSTRAINT "contratos_data_ocupacao_text" CHECK(`data_ocupacao` IS NULL OR (typeof(`data_ocupacao`)='text' AND length(trim(`data_ocupacao`))>0)) CONSTRAINT "contratos_data_ocupacao_length" CHECK(`data_ocupacao` IS NULL OR length(`data_ocupacao`)<=10) CONSTRAINT "contratos_data_ocupacao_date" CHECK(`data_ocupacao` IS NULL OR (length(`data_ocupacao`)=10 AND `data_ocupacao` GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND date(`data_ocupacao`, '+0 days') IS NOT NULL AND date(`data_ocupacao`, '+0 days')=`data_ocupacao`));--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `data_assinatura` text(10) CONSTRAINT "contratos_data_assinatura_text" CHECK(`data_assinatura` IS NULL OR (typeof(`data_assinatura`)='text' AND length(trim(`data_assinatura`))>0)) CONSTRAINT "contratos_data_assinatura_length" CHECK(`data_assinatura` IS NULL OR length(`data_assinatura`)<=10) CONSTRAINT "contratos_data_assinatura_date" CHECK(`data_assinatura` IS NULL OR (length(`data_assinatura`)=10 AND `data_assinatura` GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND date(`data_assinatura`, '+0 days') IS NOT NULL AND date(`data_assinatura`, '+0 days')=`data_assinatura`));--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `referencia_pagamento` text(40) CONSTRAINT "contratos_referencia_pagamento_text" CHECK(`referencia_pagamento` IS NULL OR (typeof(`referencia_pagamento`)='text' AND length(trim(`referencia_pagamento`))>0)) CONSTRAINT "contratos_referencia_pagamento_length" CHECK(`referencia_pagamento` IS NULL OR length(`referencia_pagamento`)<=40);--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `periodicidade_reajuste_meses` integer CONSTRAINT "contratos_periodicidade_reajuste_meses_integer" CHECK(`periodicidade_reajuste_meses` IS NULL OR typeof(`periodicidade_reajuste_meses`)='integer');--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `multa_atraso_percentual` integer CONSTRAINT "contratos_multa_atraso_percentual_integer" CHECK(`multa_atraso_percentual` IS NULL OR typeof(`multa_atraso_percentual`)='integer') CONSTRAINT "contratos_multa_atraso_percentual_range" CHECK(`multa_atraso_percentual` IS NULL OR `multa_atraso_percentual` BETWEEN 0 AND 10000);--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `juros_mensal_percentual` integer CONSTRAINT "contratos_juros_mensal_percentual_integer" CHECK(`juros_mensal_percentual` IS NULL OR typeof(`juros_mensal_percentual`)='integer') CONSTRAINT "contratos_juros_mensal_percentual_range" CHECK(`juros_mensal_percentual` IS NULL OR `juros_mensal_percentual` BETWEEN 0 AND 10000);--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `canal_envio` text(40) CONSTRAINT "contratos_canal_envio_text" CHECK(`canal_envio` IS NULL OR (typeof(`canal_envio`)='text' AND length(trim(`canal_envio`))>0)) CONSTRAINT "contratos_canal_envio_length" CHECK(`canal_envio` IS NULL OR length(`canal_envio`)<=40);--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `garantia_tipo` text(60) CONSTRAINT "contratos_garantia_tipo_text" CHECK(`garantia_tipo` IS NULL OR (typeof(`garantia_tipo`)='text' AND length(trim(`garantia_tipo`))>0)) CONSTRAINT "contratos_garantia_tipo_length" CHECK(`garantia_tipo` IS NULL OR length(`garantia_tipo`)<=60);--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `garantia_detalhe` text CONSTRAINT "contratos_garantia_detalhe_text" CHECK(`garantia_detalhe` IS NULL OR (typeof(`garantia_detalhe`)='text' AND length(trim(`garantia_detalhe`))>0));--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `regra_primeira_cobranca` text(60) CONSTRAINT "contratos_regra_primeira_cobranca_text" CHECK(`regra_primeira_cobranca` IS NULL OR (typeof(`regra_primeira_cobranca`)='text' AND length(trim(`regra_primeira_cobranca`))>0)) CONSTRAINT "contratos_regra_primeira_cobranca_length" CHECK(`regra_primeira_cobranca` IS NULL OR length(`regra_primeira_cobranca`)<=60);--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `forma_pagamento_texto` text(40) CONSTRAINT "contratos_forma_pagamento_texto_text" CHECK(`forma_pagamento_texto` IS NULL OR (typeof(`forma_pagamento_texto`)='text' AND length(trim(`forma_pagamento_texto`))>0)) CONSTRAINT "contratos_forma_pagamento_texto_length" CHECK(`forma_pagamento_texto` IS NULL OR length(`forma_pagamento_texto`)<=40);--> statement-breakpoint
ALTER TABLE `contratos` ADD COLUMN `nome_documento` text(255) CONSTRAINT "contratos_nome_documento_text" CHECK(`nome_documento` IS NULL OR (typeof(`nome_documento`)='text' AND length(trim(`nome_documento`))>0)) CONSTRAINT "contratos_nome_documento_length" CHECK(`nome_documento` IS NULL OR length(`nome_documento`)<=255);
