import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import type { Charge, Receipt } from '../../core/models/domain.models';
import { AppStore } from '../../core/services/app-store.service';
import { EntityModalService } from '../../core/services/entity-modal.service';
import { ToastService } from '../../core/services/toast.service';
import { ALL_REPORT_PORTFOLIOS, buildAccountingReportModel, inputValueToCompetence, suggestedAccountingReportFilename } from '../../core/utils/accounting-report';
import { createAccountingReportWorkbook, downloadAccountingReport, revokeAccountingReportDownload, type AccountingReportDownload } from '../../core/utils/accounting-report-workbook';
import { buildNegotiationSchedule, calculateNegotiationTotals, validateNegotiationTerms, type ChargeNegotiation, type NegotiationTerms } from '../../core/utils/charge-negotiation';
import { brl, chargeBalance, chargeTotal, formatDate, nextRecordId, normalizeSearch, receivedTotal } from '../../core/utils/domain.utils';
import { DetailDrawerComponent, type DetailRow } from '../../shared/components/detail-drawer.component';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { PageHeadingComponent } from '../../shared/components/page-heading.component';
import { StatusBadgeComponent } from '../../shared/components/status-badge.component';

type ChargeDialog = 'receipt' | 'negotiation' | 'report' | null;

@Component({
  selector: 'app-charges-page',
  imports: [FormsModule, ReactiveFormsModule, PageHeadingComponent, EmptyStateComponent, DetailDrawerComponent, StatusBadgeComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="page-enter"><app-page-heading title="Cobranças" description="Recebíveis, competências, baixas e acordos financeiros." actionLabel="Nova cobrança" (action)="modal.open('charge')" />
      <div class="charge-command-overview">
        <div class="charge-command-balance"><span>Saldo operacional</span><strong>{{ money(openBalance()) }}</strong><small>{{ receivedPercent() }}% da carteira recebida</small><div><span><b>{{ money(received()) }} baixados</b><small>de {{ money(billed()) }} faturados</small></span><i><b [style.width.%]="receivedPercent()"></b></i></div></div>
        <button class="charge-command-card charge-command-overdue" [attr.aria-pressed]="status==='Vencida'" (click)="toggleStatus('Vencida')"><span>Vencidas</span><strong>{{ count('Vencida') }}</strong><small>{{ money(totalByStatus('Vencida')) }}</small><i>!</i></button>
        <button class="charge-command-card charge-command-upcoming" [attr.aria-pressed]="status==='Próxima'" (click)="toggleStatus('Próxima')"><span>Próximas</span><strong>{{ count('Próxima') }}</strong><small>{{ money(totalByStatus('Próxima')) }}</small><i>◷</i></button>
        <button class="charge-command-card charge-command-negotiated" [attr.aria-pressed]="status==='Negociada'" (click)="toggleStatus('Negociada')"><span>Negociadas</span><strong>{{ count('Negociada') }}</strong><small>{{ money(totalByStatus('Negociada')) }}</small><i>≋</i></button>
      </div>
      <section class="table-section"><div class="table-toolbar"><label class="search-field"><span class="app-search-icon">⌕</span><input [(ngModel)]="query" placeholder="Buscar cobrança, contrato ou locatário"></label><label class="filter-select"><select [(ngModel)]="status"><option value="">Todas as situações</option><option>Vencida</option><option>Parcial</option><option>Próxima</option><option>Em aberto</option><option>Negociada</option><option>Recebida</option></select><i class="filter-select-chevron"></i></label><label class="filter-select"><select [(ngModel)]="portfolio"><option value="">Todas as carteiras</option>@for(item of store.portfolios();track item.id){<option [value]="item.name">{{item.name}}</option>}</select><i class="filter-select-chevron"></i></label><button class="secondary-button" type="button" (click)="openReport()">↓ Relatório XLSX</button>@if(query||status||portfolio){<button class="charge-clear-filters" (click)="clear()">× Limpar</button>}</div>
        @if(filtered().length){<div class="charge-ledger">@for(item of filtered();track item.id){<button class="charge-ledger-row charge-ledger-{{ slugStatus(item.status) }}" (click)="selected.set(item)"><i class="charge-ledger-marker"></i><span class="charge-ledger-identity"><span><strong>{{item.id}}</strong><small>{{item.contract}}</small></span><app-status-badge [value]="item.status"/></span><span class="charge-ledger-context"><small>Locatário / competência</small><strong>{{item.tenant}}</strong><span>{{item.competence}} · {{item.property}}</span></span><span class="charge-ledger-due"><small>Vencimento</small><strong>{{firstDue(item)}}</strong><span>{{item.units.join(', ')}}</span></span><span class="charge-ledger-values"><span><small>Total</small><b>{{money(total(item))}}</b></span><span><small>Saldo</small><strong>{{money(balance(item))}}</strong></span><i><b [style.width.%]="progress(item)"></b></i></span><b class="charge-ledger-arrow">→</b></button>}</div>}@else{<app-empty-state title="Nenhuma cobrança encontrada" description="Ajuste os filtros ou gere uma nova cobrança."/>}<footer class="table-footer"><span>Livro de recebíveis</span><span>{{filtered().length}} cobranças · {{money(filteredBalance())}}</span></footer>
      </section>
    </section>
    @if(selected();as item){<app-detail-drawer eyebrow="Cobrança" [title]="item.id" [subtitle]="item.tenant" [rows]="rows(item)" actionLabel="Registrar recebimento" [secondaryLabel]="item.status==='Recebida'?'':'Negociar saldo'" (closed)="selected.set(null)" (action)="openReceipt(item)" (secondary)="openNegotiation(item)"><section class="app-drawer-items"><h3>Composição</h3>@for(line of item.items;track $index){<div><span><strong>{{line.name}}</strong><small>Vencimento {{line.dueDate}}</small></span><span><b>{{money(line.amount)}}</b><small>Recebido {{money(line.received)}}</small></span></div>}</section>@if(store.negotiations()[item.id];as negotiation){<section class="app-negotiation-summary"><span>Acordo ativo</span><strong>{{money(negotiation.negotiatedTotal)}} em {{negotiation.installmentCount}} parcela(s)</strong><small>Primeiro vencimento: {{format(negotiation.firstDueDate)}}</small></section>}</app-detail-drawer>}

    @if(dialog()==='receipt' && activeCharge();as charge){<section class="modal-layer" role="dialog" aria-modal="true" aria-label="Registrar recebimento"><button class="drawer-backdrop" (click)="closeDialog()"></button><form class="receipt-modal" [formGroup]="receiptForm" (ngSubmit)="saveReceipt(charge)"><header><div><p class="eyebrow">Baixa financeira</p><h2>Registrar recebimento</h2></div><button class="close-button" type="button" (click)="closeDialog()">×</button></header><div class="receipt-context"><span><small>Cobrança</small><strong>{{charge.id}}</strong></span><span><small>Locatário</small><strong>{{charge.tenant}}</strong></span><span><small>Saldo atual</small><strong>{{money(balance(charge))}}</strong></span></div><section class="receipt-form-section form-grid"><label>Data do recebimento *<input type="date" formControlName="receiptDate"></label><label>Valor recebido *<input type="number" min="0.01" step="0.01" formControlName="amount"></label><label>Forma de pagamento<select formControlName="paymentMethod"><option>Pix</option><option>Transferência bancária</option><option>Boleto bancário</option></select></label><label>Conta financeira<input formControlName="financialAccount"></label><label class="full-field">Referência / observação<input formControlName="reference"></label></section><section class="allocation-section"><header><div><strong>Alocação automática</strong><small>O valor é distribuído pelos itens com saldo, na ordem de vencimento.</small></div><b>{{money(receiptAmount())}}</b></header>@for(line of allocationPreview(charge);track line.name){<div class="allocation-row"><span>{{line.name}}</span><small>saldo {{money(line.balance)}}</small><strong>{{money(line.allocation)}}</strong></div>}</section>@if(receiptError()){<p class="inline-field-error">{{receiptError()}}</p>}<footer><button class="secondary-button" type="button" (click)="closeDialog()">Cancelar</button><button class="primary-button" type="submit">Confirmar recebimento</button></footer></form></section>}

    @if(dialog()==='negotiation' && activeCharge();as charge){<section class="modal-layer" role="dialog" aria-modal="true" aria-label="Negociar cobrança"><button class="drawer-backdrop" (click)="closeDialog()"></button><form class="receipt-modal negotiation-modal" [formGroup]="negotiationForm" (ngSubmit)="saveNegotiation(charge)"><header><div><p class="eyebrow">Acordo financeiro</p><h2>Negociar saldo</h2></div><button class="close-button" type="button" (click)="closeDialog()">×</button></header><div class="negotiation-context"><div><small>Cobrança</small><strong>{{charge.id}}</strong></div><div><small>Saldo original</small><strong>{{money(balance(charge))}}</strong></div><div><small>Locatário</small><strong>{{charge.tenant}}</strong></div></div><section class="negotiation-section form-grid"><header><strong>Condições do acordo</strong><small>Defina descontos, acréscimos, entrada e parcelamento.</small></header><div class="negotiation-fields-grid"><label>Desconto<input type="number" min="0" step="0.01" formControlName="discount"></label><label>Acréscimos<input type="number" min="0" step="0.01" formControlName="surcharge"></label><label>Entrada<input type="number" min="0" step="0.01" formControlName="downPayment"></label><label>Parcelas<input type="number" min="1" max="24" formControlName="installmentCount"></label><label>Primeiro vencimento<input type="date" formControlName="firstDueDate"></label><label>Motivo<select formControlName="reason"><option>Inadimplência temporária</option><option>Renegociação comercial</option><option>Acordo extrajudicial</option><option>Outro</option></select></label></div></section><section class="negotiation-preview"><header><strong>Prévia financeira</strong><small>Valores calculados em centavos para evitar diferença de arredondamento.</small></header><div class="negotiation-preview-values"><span><small>Total negociado</small><strong>{{money(negotiationTotals().negotiatedTotal)}}</strong></span><span><small>Valor financiado</small><strong>{{money(negotiationTotals().financedAmount)}}</strong></span><span><small>Parcelas</small><strong>{{negotiationSchedule().length}}</strong></span></div><div class="app-schedule">@for(item of negotiationSchedule();track item.number){<span><b>{{item.number}}ª</b><small>{{format(item.dueDate)}}</small><strong>{{money(item.amount)}}</strong></span>}</div></section>@if(negotiationError()){<p class="inline-field-error">{{negotiationError()}}</p>}<footer><button class="secondary-button" type="button" (click)="closeDialog()">Cancelar</button><button class="primary-button" type="submit">Salvar acordo</button></footer></form></section>}

    @if(dialog()==='report'){<section class="modal-layer" role="dialog" aria-modal="true" aria-label="Relatório de aluguéis"><button class="drawer-backdrop" (click)="closeDialog()"></button><form class="receipt-modal" [formGroup]="reportForm" (ngSubmit)="generateReport()"><header><div><p class="eyebrow">Exportação contábil</p><h2>Relação de aluguéis</h2></div><button class="close-button" type="button" (click)="closeDialog()">×</button></header><section class="receipt-form-section form-grid"><label>Competência *<input type="month" formControlName="competence"></label><label>Carteira<select formControlName="portfolioScope"><option [value]="allPortfolios">Todas as carteiras</option>@for(item of store.portfolios();track item.id){<option [value]="item.name">{{item.name}}</option>}</select></label><p class="form-help full-field">O arquivo contém somente os itens classificados como aluguel, mantendo o modelo contábil original.</p></section>@if(reportError()){<p class="inline-field-error">{{reportError()}}</p>}<footer><button class="secondary-button" type="button" (click)="closeDialog()">Cancelar</button><button class="primary-button" type="submit" [disabled]="reportLoading()">{{reportLoading()?'Gerando…':'Gerar e baixar XLSX'}}</button></footer></form></section>}
  `,
})
export class ChargesPage {
  readonly store=inject(AppStore);readonly modal=inject(EntityModalService);private readonly toast=inject(ToastService);private readonly fb=inject(FormBuilder);readonly selected=signal<Charge|null>(null);readonly activeCharge=signal<Charge|null>(null);readonly dialog=signal<ChargeDialog>(null);query='';status='';portfolio='';readonly receiptError=signal('');readonly negotiationError=signal('');readonly reportError=signal('');readonly reportLoading=signal(false);readonly allPortfolios=ALL_REPORT_PORTFOLIOS;private lastDownload:AccountingReportDownload|null=null;
  readonly billed=computed(()=>this.store.charges().reduce((s,c)=>s+chargeTotal(c),0));readonly received=computed(()=>this.store.charges().reduce((s,c)=>s+receivedTotal(c),0));readonly openBalance=computed(()=>this.store.charges().reduce((s,c)=>s+this.balance(c),0));readonly receivedPercent=computed(()=>Math.round(this.received()/Math.max(1,this.billed())*100));readonly filtered=computed(()=>{const q=normalizeSearch(this.query);return this.store.charges().filter(c=>(!this.status||c.status===this.status)&&(!this.portfolio||c.portfolio===this.portfolio)&&(!q||normalizeSearch(`${c.id} ${c.contract} ${c.tenant} ${c.property}`).includes(q)))});readonly filteredBalance=computed(()=>this.filtered().reduce((s,c)=>s+this.balance(c),0));
  readonly receiptForm=this.fb.group({receiptDate:['2026-08-12',Validators.required],amount:[0,[Validators.required,Validators.min(.01)]],paymentMethod:['Pix'],financialAccount:['Conta de Recebíveis'],reference:['']});
  readonly negotiationForm=this.fb.group({discount:[0],surcharge:[0],downPayment:[0],installmentCount:[3,[Validators.required,Validators.min(1),Validators.max(24)]],firstDueDate:['2026-09-12',Validators.required],reason:['Inadimplência temporária']});
  readonly reportForm=this.fb.group({competence:['2026-08',Validators.required],portfolioScope:[ALL_REPORT_PORTFOLIOS,Validators.required]});
  money(v:number){return brl.format(v)}total(c:Charge){return chargeTotal(c)}balance(c:Charge){const negotiation=this.store.negotiations()[c.id];if(!negotiation)return chargeBalance(c);const receiptTotal=(this.store.receipts()[c.id]??[]).reduce((sum,receipt)=>sum+receipt.amount,0);return Math.max(0,negotiation.negotiatedTotal-(receiptTotal-(negotiation.priorReceiptAmount??0)))}progress(c:Charge){const negotiation=this.store.negotiations()[c.id];if(!negotiation)return Math.round(receivedTotal(c)/Math.max(1,chargeTotal(c))*100);return Math.round((negotiation.negotiatedTotal-this.balance(c))/Math.max(1,negotiation.negotiatedTotal)*100)}format(v:string){return formatDate(v)}slugStatus(v:string){return normalizeSearch(v).replace(/\s+/g,'-')}firstDue(c:Charge){return [...c.items].sort((a,b)=>(a.dueDateIso||'').localeCompare(b.dueDateIso||''))[0]?.dueDate||'Não informado'}count(status:string){return this.store.charges().filter(c=>c.status===status).length}totalByStatus(status:string){return this.store.charges().filter(c=>c.status===status).reduce((s,c)=>s+this.balance(c),0)}toggleStatus(s:string){this.status=this.status===s?'':s}clear(){this.query='';this.status='';this.portfolio=''}
  rows(c:Charge):DetailRow[]{return[{label:'Contrato',value:c.contract},{label:'Carteira',value:c.portfolio},{label:'Imóvel',value:c.property},{label:'Unidades',value:c.units.join(', ')},{label:'Competência',value:c.competence},{label:'Situação',value:c.status},{label:'Total',value:this.money(this.total(c))},{label:'Recebido',value:this.money(receivedTotal(c))},{label:'Saldo',value:this.money(this.balance(c))}]}
  openReceipt(c:Charge){this.activeCharge.set(c);this.selected.set(null);this.receiptError.set('');this.receiptForm.reset({receiptDate:'2026-08-12',amount:this.balance(c),paymentMethod:'Pix',financialAccount:'Conta de Recebíveis',reference:''});this.dialog.set('receipt')}
  receiptAmount(){return Number(this.receiptForm.value.amount)||0}allocationPreview(c:Charge){let remaining=this.receiptAmount();return c.items.map(item=>{const balance=Math.max(0,item.amount-item.received);const allocation=Math.min(balance,Math.max(0,remaining));remaining-=allocation;return{name:item.name,balance,allocation}})}
  saveReceipt(c:Charge){this.receiptError.set('');const amount=this.receiptAmount();if(this.receiptForm.invalid||amount>this.balance(c)+.009){this.receiptError.set(amount>this.balance(c)+.009?'O valor não pode superar o saldo da cobrança.':'Preencha a data e um valor válido.');return}const v=this.receiptForm.getRawValue();const receipt:Receipt={id:nextRecordId('REC',Object.values(this.store.receipts()).flat()),chargeId:c.id,receiptDate:v.receiptDate||'',creditDate:v.receiptDate||'',amount,discount:0,interest:0,paymentMethod:v.paymentMethod||'Pix',financialAccount:v.financialAccount||'',reference:v.reference||'',thirdPartyPayer:'',proofName:'',note:'',allocations:this.allocationPreview(c).map((a,index)=>({itemIndex:index,amount:a.allocation})).filter(a=>a.amount>0)};this.store.saveReceipt(receipt);this.toast.show('Recebimento registrado',receipt.id);this.closeDialog()}
  openNegotiation(c:Charge){this.activeCharge.set(c);this.selected.set(null);this.negotiationError.set('');this.negotiationForm.reset({discount:0,surcharge:0,downPayment:0,installmentCount:3,firstDueDate:'2026-09-12',reason:'Inadimplência temporária'});this.dialog.set('negotiation')}
  private terms(c:Charge):NegotiationTerms{const v=this.negotiationForm.getRawValue();return{originalBalance:this.balance(c),discount:Number(v.discount)||0,surcharge:Number(v.surcharge)||0,downPayment:Number(v.downPayment)||0,installmentCount:Number(v.installmentCount)||0,firstDueDate:v.firstDueDate||''}}
  negotiationTotals(){const c=this.activeCharge();return calculateNegotiationTotals(c?this.terms(c):{originalBalance:0,discount:0,surcharge:0,downPayment:0})}negotiationSchedule(){const c=this.activeCharge();if(!c)return[];const t=this.terms(c);return buildNegotiationSchedule(t.firstDueDate,t.installmentCount,calculateNegotiationTotals(t).financedAmount)}
  saveNegotiation(c:Charge){const terms=this.terms(c);const error=validateNegotiationTerms(terms,'2026-08-12');this.negotiationError.set(error);if(error)return;const totals=calculateNegotiationTotals(terms);const v=this.negotiationForm.getRawValue();const negotiation:ChargeNegotiation={id:`NEG-${c.id}`,chargeId:c.id,...terms,...totals,schedule:buildNegotiationSchedule(terms.firstDueDate,terms.installmentCount,totals.financedAmount),reason:v.reason||'Renegociação comercial',paymentMethod:'Boleto bancário',notes:'',createdAt:'2026-08-12T12:00:00.000Z',updatedAt:'2026-08-12T12:00:00.000Z'};this.store.saveNegotiation(negotiation);this.toast.show('Acordo financeiro salvo',negotiation.id);this.closeDialog()}
  openReport(){this.reportError.set('');this.dialog.set('report')}
  async generateReport(){if(this.reportForm.invalid)return;this.reportLoading.set(true);this.reportError.set('');try{const v=this.reportForm.getRawValue();const competence=inputValueToCompetence(v.competence||'');const model=buildAccountingReportModel({competence,portfolioScope:v.portfolioScope||ALL_REPORT_PORTFOLIOS,portfolios:this.store.portfolios(),properties:this.store.properties(),tenants:this.store.tenants(),charges:this.store.charges()});const bytes=await createAccountingReportWorkbook(model);revokeAccountingReportDownload(this.lastDownload);const portfolioName=v.portfolioScope===ALL_REPORT_PORTFOLIOS?undefined:v.portfolioScope||undefined;this.lastDownload=downloadAccountingReport(bytes,suggestedAccountingReportFilename(competence,portfolioName));this.toast.show('Relatório contábil gerado',this.lastDownload.filename);this.closeDialog()}catch(error){this.reportError.set(error instanceof Error?error.message:'Não foi possível gerar o relatório.')}finally{this.reportLoading.set(false)}}
  closeDialog(){this.dialog.set(null);this.activeCharge.set(null);this.receiptError.set('');this.negotiationError.set('')}
}
