import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { Property } from '../../core/models/domain.models';
import { FALLBACK_PROPERTY_IMAGE, PROPERTY_IMAGES } from '../../core/data/demo-data';
import { AppStore } from '../../core/services/app-store.service';
import { EntityModalService } from '../../core/services/entity-modal.service';
import { normalizeSearch } from '../../core/utils/domain.utils';
import { DetailDrawerComponent, type DetailRow } from '../../shared/components/detail-drawer.component';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { PageHeadingComponent } from '../../shared/components/page-heading.component';

@Component({ selector: 'app-properties-page', imports: [FormsModule, PageHeadingComponent, EmptyStateComponent, DetailDrawerComponent], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<section class="page-enter"><app-page-heading title="Imóveis" description="Ativos físicos e disponibilidade por endereço." actionLabel="Novo imóvel" (action)="modal.open('property')" />
    <div class="property-insight-strip"><div class="property-insight-main"><span>Portfólio imobiliário</span><strong>{{ store.properties().length }} imóveis</strong><small>Distribuídos em {{ store.portfolios().length }} carteiras.</small></div><div><span>Unidades</span><strong>{{ store.units().length }}</strong><small>espaços cadastrados</small></div><div class="property-insight-available"><span>Disponíveis</span><strong>{{ available() }}</strong><small>unidades livres</small></div><div class="property-insight-occupancy"><span>Ocupação</span><strong>{{ occupancy() }}%</strong><i><b [style.width.%]="occupancy()"></b></i><small>inventário ocupado</small></div></div>
    <section class="table-section"><div class="table-toolbar"><label class="search-field"><span class="app-search-icon">⌕</span><input [(ngModel)]="query" placeholder="Buscar imóvel ou endereço"></label><label class="filter-select"><span class="filter-select-icon">◇</span><select [(ngModel)]="portfolio"><option value="">Todas as carteiras</option>@for (item of store.portfolios(); track item.id) { <option [value]="item.name">{{ item.name }}</option> }</select><i class="filter-select-chevron"></i></label></div>
    @if (filtered().length) { <div class="property-card-grid">@for (item of filtered(); track item.id) { <button class="property-card" type="button" (click)="selected.set(item)"><span class="property-card-media"><img [src]="image(item)" [alt]="item.name"><i class="property-card-id">{{ item.id }}</i><i class="property-card-availability" [class.property-card-full]="availableFor(item) === 0">{{ availableFor(item) ? availableFor(item)+' disponível(is)' : 'Ocupado' }}</i></span><span class="property-card-body"><strong>{{ item.name }}</strong><span class="property-card-address"><i></i>{{ item.address }}</span><span class="property-card-meta"><b>{{ item.portfolio }}</b><span>{{ item.units || unitsFor(item).length }} un.</span></span><span class="property-card-occupancy"><span><strong>{{ occupancyFor(item) }}% ocupado</strong><small>{{ occupiedFor(item) }} de {{ unitsFor(item).length }} unidades</small></span><i><b [style.width.%]="occupancyFor(item)"></b></i></span></span></button> }</div> } @else { <app-empty-state title="Nenhum imóvel encontrado" description="Altere os filtros ou cadastre um novo imóvel." /> }
    <footer class="table-footer"><span>Portfólio visual</span><span>{{ filtered().length }} imóveis</span></footer></section></section>
    @if (selected(); as item) { <app-detail-drawer eyebrow="Imóvel" [title]="item.name" [subtitle]="item.address" [rows]="rows(item)" actionLabel="Editar imóvel" (closed)="selected.set(null)" (action)="modal.open('property', item); selected.set(null)" /> }`,
})
export class PropertiesPage {
  readonly store = inject(AppStore); readonly modal = inject(EntityModalService); readonly selected = signal<Property | null>(null); query = ''; portfolio = '';
  readonly filtered = computed(() => { const q = normalizeSearch(this.query); return this.store.properties().filter(p => (!this.portfolio || p.portfolio === this.portfolio) && (!q || normalizeSearch(`${p.name} ${p.address} ${p.portfolio}`).includes(q))); });
  readonly available = computed(() => this.store.units().filter(u => !u.occupied).length); readonly occupancy = computed(() => Math.round((this.store.units().length - this.available()) / Math.max(1, this.store.units().length) * 100));
  image(p: Property): string { return PROPERTY_IMAGES[p.id] ?? FALLBACK_PROPERTY_IMAGE; } unitsFor(p: Property) { return this.store.units().filter(u => u.property === p.name); } occupiedFor(p: Property): number { return this.unitsFor(p).filter(u => u.occupied).length; } availableFor(p: Property): number { return this.unitsFor(p).filter(u => !u.occupied).length; } occupancyFor(p: Property): number { const units = this.unitsFor(p); return units.length ? Math.round(this.occupiedFor(p) / units.length * 100) : 0; }
  rows(p: Property): DetailRow[] { return [{label:'Código',value:p.id},{label:'Carteira',value:p.portfolio},{label:'Endereço',value:p.address},{label:'Tipo',value:p.propertyType || 'Imóvel comercial'},{label:'Unidades',value:String(this.unitsFor(p).length)},{label:'Disponíveis',value:String(this.availableFor(p))}]; }
}
