import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import type { RealEstateAgency, Tenant } from '../../core/models/domain.models';
import { AppStore } from '../../core/services/app-store.service';
import { EntityModalService } from '../../core/services/entity-modal.service';
import { ToastService } from '../../core/services/toast.service';
import { brl, nextRecordId, normalizeSearch } from '../../core/utils/domain.utils';
import { DetailDrawerComponent, type DetailRow } from '../../shared/components/detail-drawer.component';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { PageHeadingComponent } from '../../shared/components/page-heading.component';

@Component({ selector:'app-tenants-page',imports:[FormsModule,ReactiveFormsModule,PageHeadingComponent,EmptyStateComponent,DetailDrawerComponent],changeDetection:ChangeDetectionStrategy.OnPush,
template:`<section class="page-enter"><app-page-heading title="Locatários" description="Pessoas, empresas, imobiliárias e vínculos contratuais." actionLabel="Novo locatário" (action)="modal.open('tenant')" />
<div class="tenant-overview"><div class="tenant-overview-intro"><span>Relacionamento locatício</span><strong>{{store.tenants().length}} locatários</strong><small>Gestão de contratos e responsáveis.</small></div><div class="tenant-overview-revenue"><span>Receita contratada</span><strong>{{money(monthlyRent())}}</strong><small>aluguel mensal ativo</small></div><button class="tenant-overview-active" (click)="relationship='active'"><span>Com contrato</span><strong>{{activeCount()}}</strong><small>vínculos ativos</small><i>✓</i></button><button class="tenant-overview-unlinked" (click)="relationship='unlinked'"><span>Sem contrato</span><strong>{{unlinkedCount()}}</strong><small>aguardando vínculo</small><i>!</i></button></div>
<section class="tenant-agency-hub"><header><span class="tenant-agency-hub-icon">⌂</span><div><p class="eyebrow">Rede de atendimento</p><h2>Imobiliárias responsáveis</h2><span>Filtre os locatários pelo parceiro que conduz o relacionamento.</span></div><button class="secondary-button" (click)="agencyModal.set(true)">＋ Nova imobiliária</button></header><div class="tenant-agency-grid">@for(agency of store.agencies();track agency.id){<button class="tenant-agency-card" [attr.aria-pressed]="agencyId===agency.id" (click)="agencyId=agencyId===agency.id?'':agency.id"><span class="tenant-agency-monogram">{{initials(agency.tradeName||agency.name)}}</span><span class="tenant-agency-copy"><small>{{agency.id}}</small><strong>{{agency.tradeName||agency.name}}</strong><span>{{agency.contactName}}</span></span><span class="tenant-agency-count"><strong>{{tenantCount(agency)}}</strong><small>loc.</small></span></button>}</div><footer><span>✓ {{store.agencies().length}} imobiliárias ativas</span><button [attr.aria-pressed]="agencyId==='none'" (click)="agencyId=agencyId==='none'?'':'none'">Sem imobiliária responsável</button></footer></section>
<section class="table-section"><div class="table-toolbar"><label class="search-field"><span class="app-search-icon">⌕</span><input [(ngModel)]="query" placeholder="Buscar locatário ou documento"></label><label class="filter-select"><select [(ngModel)]="relationship"><option value="">Todos os vínculos</option><option value="active">Com contrato</option><option value="unlinked">Sem contrato</option></select><i class="filter-select-chevron"></i></label></div>
@if(filtered().length){<div class="tenant-card-grid">@for(item of filtered();track item.id){<article class="tenant-card" [class.tenant-card-unlinked]="item.contracts===0"><button class="tenant-card-open" (click)="selected.set(item)"><span class="tenant-card-head"><span class="tenant-card-avatar">{{initials(item.name)}}</span><span class="tenant-card-identity"><span><b>{{item.type}}</b><small>{{item.id}}</small></span><strong>{{item.name}}</strong><small>{{item.document}}</small></span><span class="tenant-relationship-badge"><i></i>{{item.contracts?item.contracts+' contrato(s)':'Sem contrato'}}</span></span><span class="tenant-card-agency" [class.tenant-card-agency-missing]="!item.responsibleAgencyId"><span>⌂</span><span><small>Imobiliária responsável</small><strong>{{agencyName(item)}}</strong></span></span>@if(contractFor(item);as contract){<span class="tenant-card-contract"><span><small>Contrato</small><strong>{{contract.id}}</strong></span><span><small>Imóvel</small><strong>{{contract.property}}</strong></span><span><small>Unidade</small><strong>{{contract.units.join(', ')}}</strong></span></span><span class="tenant-card-financial"><span><small>Aluguel mensal</small><strong>{{money(contract.rent)}}</strong></span><span><small>Próximo vencimento</small><strong>Dia {{contract.due}}</strong></span></span>}@else{<span class="tenant-card-empty-link"><i>＋</i><span><strong>Locatário sem contrato</strong><small>Cadastre um vínculo para iniciar a cobrança.</small></span></span>}<span class="tenant-card-arrow">Abrir relacionamento <b>→</b></span></button><footer><span>{{item.email||item.phone||'Contato não informado'}}</span><button (click)="modal.open('tenant',item)">Editar cadastro</button></footer></article>}</div>}@else{<app-empty-state title="Nenhum locatário encontrado" description="Ajuste os filtros ou cadastre um novo locatário."/>}<footer class="table-footer"><span>Relacionamentos ativos</span><span>{{filtered().length}} locatários</span></footer></section></section>
@if(selected();as item){<app-detail-drawer eyebrow="Locatário" [title]="item.name" [subtitle]="item.document" [rows]="rows(item)" actionLabel="Editar cadastro" (closed)="selected.set(null)" (action)="modal.open('tenant',item);selected.set(null)"/>}
@if(agencyModal()){<section class="modal-layer" role="dialog" aria-modal="true" aria-label="Nova imobiliária"><button class="drawer-backdrop" (click)="agencyModal.set(false)"></button><form class="receipt-modal entity-modal agency-modal" [formGroup]="agencyForm" (ngSubmit)="saveAgency()"><header class="entity-form-hero"><span class="entity-form-mark">⌂</span><div><p class="eyebrow">Rede de atendimento</p><h2>Nova imobiliária</h2><span>Cadastre o parceiro responsável pelos locatários.</span></div><button class="close-button" type="button" (click)="agencyModal.set(false)">×</button></header><div class="entity-grid form-grid"><label>Razão social *<input formControlName="name"></label><label>Nome fantasia<input formControlName="tradeName"></label><label>CNPJ *<input formControlName="document"></label><label>CRECI *<input formControlName="creci"></label><label>Contato *<input formControlName="contactName"></label><label>Telefone<input formControlName="phone"></label><label class="full-field">E-mail<input type="email" formControlName="email"></label></div><footer class="entity-form-footer"><div></div><button class="secondary-button" type="button" (click)="agencyModal.set(false)">Cancelar</button><button class="primary-button" type="submit">Salvar imobiliária</button></footer></form></section>}`})
export class TenantsPage{
 readonly store=inject(AppStore);readonly modal=inject(EntityModalService);private readonly toast=inject(ToastService);private readonly fb=inject(FormBuilder);readonly selected=signal<Tenant|null>(null);readonly agencyModal=signal(false);query='';relationship='';agencyId='';
 readonly monthlyRent=computed(()=>this.store.contracts().reduce((s,c)=>s+c.rent,0));readonly activeCount=computed(()=>this.store.tenants().filter(t=>t.contracts>0).length);readonly unlinkedCount=computed(()=>this.store.tenants().length-this.activeCount());
 readonly filtered=computed(()=>{const q=normalizeSearch(this.query);return this.store.tenants().filter(t=>(!this.relationship||(this.relationship==='active'?t.contracts>0:t.contracts===0))&&(!this.agencyId||(this.agencyId==='none'?!t.responsibleAgencyId:t.responsibleAgencyId===this.agencyId))&&(!q||normalizeSearch(`${t.name} ${t.document} ${t.tradeName||''}`).includes(q)));});
 readonly agencyForm=this.fb.group({name:['',Validators.required],tradeName:[''],document:['',Validators.required],creci:['',Validators.required],contactName:['',Validators.required],phone:[''],email:['']});
 money(v:number){return brl.format(v)} initials(v:string){return v.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()} tenantCount(a:RealEstateAgency){return this.store.tenants().filter(t=>t.responsibleAgencyId===a.id).length} agencyName(t:Tenant){const a=this.store.agencies().find(a=>a.id===t.responsibleAgencyId);return a?.tradeName||a?.name||'Não vinculada'} contractFor(t:Tenant){return this.store.contracts().find(c=>c.tenant===t.name)}
 rows(t:Tenant):DetailRow[]{const c=this.contractFor(t);return[{label:'Código',value:t.id},{label:'Tipo',value:t.type},{label:'Documento',value:t.document},{label:'Imobiliária',value:this.agencyName(t)},{label:'Contratos',value:String(t.contracts)},{label:'Imóvel vinculado',value:c?.property||'Sem contrato'},{label:'Contato',value:t.email||t.phone||'Não informado'}]}
 saveAgency(){if(this.agencyForm.invalid){this.agencyForm.markAllAsTouched();return}const v=this.agencyForm.getRawValue();const item:RealEstateAgency={id:nextRecordId('IMB',this.store.agencies()),name:v.name||'',tradeName:v.tradeName||undefined,document:v.document||'',creci:v.creci||'',contactName:v.contactName||'',phone:v.phone||undefined,email:v.email||undefined};this.store.addAgency(item);this.toast.show('Imobiliária salva com sucesso',item.id);this.agencyForm.reset();this.agencyModal.set(false)}
}
