import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { Unit } from '../../core/models/domain.models';
import { FALLBACK_PROPERTY_IMAGE, PROPERTY_IMAGES } from '../../core/data/demo-data';
import { AppStore } from '../../core/services/app-store.service';
import { EntityModalService } from '../../core/services/entity-modal.service';
import { normalizeSearch } from '../../core/utils/domain.utils';
import { DetailDrawerComponent, type DetailRow } from '../../shared/components/detail-drawer.component';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { PageHeadingComponent } from '../../shared/components/page-heading.component';

@Component({ selector: 'app-units-page', imports: [FormsModule, PageHeadingComponent, EmptyStateComponent, DetailDrawerComponent], changeDetection: ChangeDetectionStrategy.OnPush,
template: `<section class="page-enter"><app-page-heading title="Unidades" description="Espaços locáveis, áreas e situação de ocupação." actionLabel="Nova unidade" (action)="modal.open('unit')" />
<div class="unit-overview"><div class="unit-overview-intro"><span>Inventário operacional</span><strong>{{ store.units().length }} unidades</strong><small>Em {{ store.properties().length }} imóveis cadastrados.</small></div><div class="unit-overview-available"><span>Disponíveis</span><strong>{{ available() }}</strong><small>prontas para locação</small></div><div><span>Ocupadas</span><strong>{{ occupied() }}</strong><small>com vínculo ativo</small></div><div class="unit-overview-occupancy"><span>Ocupação</span><strong>{{ occupancy() }}%</strong><i><b [style.width.%]="occupancy()"></b></i><small>do inventário</small></div></div>
<section class="table-section"><div class="table-toolbar"><label class="search-field"><span class="app-search-icon">⌕</span><input [(ngModel)]="query" placeholder="Buscar unidade ou imóvel"></label><label class="filter-select"><select [(ngModel)]="status"><option value="">Todas as situações</option><option value="occupied">Ocupadas</option><option value="available">Disponíveis</option></select><i class="filter-select-chevron"></i></label><label class="filter-select"><select [(ngModel)]="property"><option value="">Todos os imóveis</option>@for (item of store.properties(); track item.id) { <option [value]="item.name">{{ item.name }}</option> }</select><i class="filter-select-chevron"></i></label></div>
@if (filtered().length) { <div class="unit-card-grid">@for (item of filtered(); track item.id) { <article class="unit-card" [class.unit-card-available]="!item.occupied"><button class="unit-card-open" (click)="selected.set(item)"><span class="unit-card-media"><img [src]="image(item)" [alt]="item.property"><i class="unit-card-id">{{ item.id }}</i><span class="status unit-status" [class.available]="!item.occupied">{{ item.occupied ? 'Ocupada' : 'Disponível' }}</span></span><span class="unit-card-body"><span class="unit-card-property">{{ item.property }}</span><strong>{{ item.name }}</strong><span class="unit-card-metrics"><span><small>Área privativa</small><b>{{ item.area }} m²</b></span><span><small>Carteira</small><b>{{ item.portfolio }}</b></span></span></span></button><footer><span>{{ item.occupied ? contractFor(item) : 'Sem contrato ativo' }}</span><button (click)="modal.open('unit', item)">Editar</button></footer></article> }</div> } @else { <app-empty-state title="Nenhuma unidade encontrada" description="Ajuste os filtros ou cadastre uma unidade." /> }<footer class="table-footer"><span>Inventário locável</span><span>{{ filtered().length }} unidades</span></footer></section></section>
@if (selected(); as item) { <app-detail-drawer eyebrow="Unidade" [title]="item.name" [subtitle]="item.property" [rows]="rows(item)" actionLabel="Editar unidade" (closed)="selected.set(null)" (action)="modal.open('unit', item); selected.set(null)" /> }` })
export class UnitsPage {
 readonly store=inject(AppStore); readonly modal=inject(EntityModalService); readonly selected=signal<Unit|null>(null); query=''; status=''; property='';
 readonly occupied=computed(()=>this.store.units().filter(u=>u.occupied).length); readonly available=computed(()=>this.store.units().length-this.occupied()); readonly occupancy=computed(()=>Math.round(this.occupied()/Math.max(1,this.store.units().length)*100));
 readonly filtered=computed(()=>{const q=normalizeSearch(this.query);return this.store.units().filter(u=>(!this.status||(this.status==='occupied'?u.occupied:!u.occupied))&&(!this.property||u.property===this.property)&&(!q||normalizeSearch(`${u.name} ${u.property} ${u.portfolio}`).includes(q)));});
 image(u:Unit):string{const p=this.store.properties().find(p=>p.name===u.property);return p?PROPERTY_IMAGES[p.id]??FALLBACK_PROPERTY_IMAGE:FALLBACK_PROPERTY_IMAGE;} contractFor(u:Unit):string{return this.store.contracts().find(c=>c.property===u.property&&c.units.includes(u.name))?.id??'Vínculo ativo';}
 rows(u:Unit):DetailRow[]{return[{label:'Código',value:u.id},{label:'Imóvel',value:u.property},{label:'Carteira',value:u.portfolio},{label:'Área',value:`${u.area} m²`},{label:'Situação',value:u.occupied?'Ocupada':'Disponível'},{label:'Contrato',value:u.occupied?this.contractFor(u):'Sem contrato'}];}
}
