import { relations } from 'drizzle-orm';
import * as s from './schema.ts';

// Associative entities remain first-class; no flattened implicit many-to-many writes.
export const usuariosRelations = relations(s.usuarios, ({many}) => ({
  permissoes: many(s.usuario_permissoes,{relationName:'usuario_permissoes_alvo'}),
  permissoesConcedidas: many(s.usuario_permissoes,{relationName:'usuario_permissoes_concedente'}),
}));
export const usuarioPermissoesRelations = relations(s.usuario_permissoes, ({one}) => ({
  usuario: one(s.usuarios,{fields:[s.usuario_permissoes.usuario_id],references:[s.usuarios.id],relationName:'usuario_permissoes_alvo'}),
  concedente: one(s.usuarios,{fields:[s.usuario_permissoes.concedida_por],references:[s.usuarios.id],relationName:'usuario_permissoes_concedente'}),
}));
export const carteirasRelations = relations(s.carteiras, ({many}) => ({ imoveis: many(s.imoveis) }));
export const imoveisRelations = relations(s.imoveis, ({one,many}) => ({ carteira: one(s.carteiras,{fields:[s.imoveis.carteira_id],references:[s.carteiras.id]}), unidades:many(s.unidades),contratos:many(s.contratos),obras:many(s.obras),documentos:many(s.documento_imovel_vinculos) }));
export const unidadesRelations = relations(s.unidades, ({one,many}) => ({ imovel:one(s.imoveis,{fields:[s.unidades.imovel_id],references:[s.imoveis.id]}),contratos:many(s.contrato_unidades),obras:many(s.obras) }));
export const imobiliariasRelations = relations(s.imobiliarias,({many})=>({locatarios:many(s.locatarios)}));
export const locatariosRelations = relations(s.locatarios,({one,many})=>({imobiliaria:one(s.imobiliarias,{fields:[s.locatarios.imobiliaria_id],references:[s.imobiliarias.id]}),contratos:many(s.contratos)}));
export const contratosRelations = relations(s.contratos,({one,many})=>({imovel:one(s.imoveis,{fields:[s.contratos.imovel_id],references:[s.imoveis.id]}),locatario:one(s.locatarios,{fields:[s.contratos.locatario_id],references:[s.locatarios.id]}),unidades:many(s.contrato_unidades),encargos:many(s.contrato_encargos),cobrancas:many(s.cobrancas)}));
export const contratoUnidadesRelations = relations(s.contrato_unidades,({one})=>({contrato:one(s.contratos,{fields:[s.contrato_unidades.contrato_id],references:[s.contratos.id]}),unidade:one(s.unidades,{fields:[s.contrato_unidades.unidade_id],references:[s.unidades.id]})}));
export const encargosRelations = relations(s.contrato_encargos,({one,many})=>({contrato:one(s.contratos,{fields:[s.contrato_encargos.contrato_id],references:[s.contratos.id]}),itens:many(s.cobranca_itens)}));
export const cobrancasRelations = relations(s.cobrancas,({one,many})=>({contrato:one(s.contratos,{fields:[s.cobrancas.contrato_id],references:[s.contratos.id]}),itens:many(s.cobranca_itens),recebimentos:many(s.recebimentos),negociacoes:many(s.negociacoes)}));
export const itensRelations = relations(s.cobranca_itens,({one,many})=>({cobranca:one(s.cobrancas,{fields:[s.cobranca_itens.cobranca_id],references:[s.cobrancas.id]}),encargo:one(s.contrato_encargos,{fields:[s.cobranca_itens.contrato_encargo_id],references:[s.contrato_encargos.id]}),alocacoes:many(s.recebimento_alocacoes)}));
export const recebimentosRelations = relations(s.recebimentos,({one,many})=>({cobranca:one(s.cobrancas,{fields:[s.recebimentos.cobranca_id],references:[s.cobrancas.id]}),alocacoes:many(s.recebimento_alocacoes),conta:one(s.contas_financeiras,{fields:[s.recebimentos.conta_financeira_id],references:[s.contas_financeiras.id]})}));
export const alocacoesRelations = relations(s.recebimento_alocacoes,({one})=>({recebimento:one(s.recebimentos,{fields:[s.recebimento_alocacoes.recebimento_id],references:[s.recebimentos.id]}),item:one(s.cobranca_itens,{fields:[s.recebimento_alocacoes.cobranca_item_id],references:[s.cobranca_itens.id]}),parcela:one(s.negociacao_parcelas,{fields:[s.recebimento_alocacoes.negociacao_parcela_id],references:[s.negociacao_parcelas.id]})}));
export const negociacoesRelations = relations(s.negociacoes,({one,many})=>({cobranca:one(s.cobrancas,{fields:[s.negociacoes.cobranca_id],references:[s.cobrancas.id]}),parcelas:many(s.negociacao_parcelas),anterior:one(s.negociacoes,{fields:[s.negociacoes.negociacao_anterior_id],references:[s.negociacoes.id],relationName:'negociacao_versao'})}));
export const parcelasRelations = relations(s.negociacao_parcelas,({one,many})=>({negociacao:one(s.negociacoes,{fields:[s.negociacao_parcelas.negociacao_id],references:[s.negociacoes.id]}),alocacoes:many(s.recebimento_alocacoes)}));
export const fornecedoresRelations = relations(s.fornecedores,({many})=>({despesas:many(s.despesas)}));
export const despesasRelations = relations(s.despesas,({one,many})=>({fornecedor:one(s.fornecedores,{fields:[s.despesas.fornecedor_id],references:[s.fornecedores.id]}),categoria:one(s.categorias_despesa,{fields:[s.despesas.categoria_id],references:[s.categorias_despesa.id]}),pagamentos:many(s.pagamentos_despesa),contratacao:one(s.obra_contratacoes),documentos:many(s.documento_vinculos)}));
export const pagamentosRelations = relations(s.pagamentos_despesa,({one,many})=>({despesa:one(s.despesas,{fields:[s.pagamentos_despesa.despesa_id],references:[s.despesas.id]}),conta:one(s.contas_financeiras,{fields:[s.pagamentos_despesa.conta_financeira_id],references:[s.contas_financeiras.id]}),documentos:many(s.documento_vinculos)}));
export const contratacoesRelations = relations(s.obra_contratacoes,({one})=>({despesa:one(s.despesas,{fields:[s.obra_contratacoes.despesa_id],references:[s.despesas.id]}),obra:one(s.obras,{fields:[s.obra_contratacoes.obra_id],references:[s.obras.id]})}));
export const obrasRelations = relations(s.obras,({one,many})=>({imovel:one(s.imoveis,{fields:[s.obras.imovel_id],references:[s.imoveis.id]}),unidade:one(s.unidades,{fields:[s.obras.unidade_id],references:[s.unidades.id]}),responsavel:one(s.profissionais,{fields:[s.obras.responsavel_profissional_id],references:[s.profissionais.id]}),atividades:many(s.obra_atividades),equipe:many(s.obra_alocacoes_equipe),contratacoes:many(s.obra_contratacoes),socios:many(s.obra_socios),aportes:many(s.aportes),ajustes:many(s.obra_ajustes_caixa),diario:many(s.obra_diario),pendencias:many(s.obra_pendencias)}));
export const atividadesRelations = relations(s.obra_atividades,({one,many})=>({obra:one(s.obras,{fields:[s.obra_atividades.obra_id],references:[s.obras.id]}),responsavel:one(s.profissionais,{fields:[s.obra_atividades.responsavel_profissional_id],references:[s.profissionais.id]}),equipe:many(s.obra_equipe_atividades)}));
export const equipeRelations = relations(s.obra_alocacoes_equipe,({one,many})=>({obra:one(s.obras,{fields:[s.obra_alocacoes_equipe.obra_id],references:[s.obras.id]}),profissional:one(s.profissionais,{fields:[s.obra_alocacoes_equipe.profissional_id],references:[s.profissionais.id]}),atividades:many(s.obra_equipe_atividades)}));
export const equipeAtividadesRelations = relations(s.obra_equipe_atividades,({one})=>({alocacao:one(s.obra_alocacoes_equipe,{fields:[s.obra_equipe_atividades.alocacao_id],references:[s.obra_alocacoes_equipe.id]}),atividade:one(s.obra_atividades,{fields:[s.obra_equipe_atividades.atividade_id],references:[s.obra_atividades.id]})}));
export const sociosRelations = relations(s.socios,({many})=>({participacoes:many(s.obra_socios)}));
export const participacoesRelations = relations(s.obra_socios,({one,many})=>({obra:one(s.obras,{fields:[s.obra_socios.obra_id],references:[s.obras.id]}),socio:one(s.socios,{fields:[s.obra_socios.socio_id],references:[s.socios.id]}),cotas:many(s.aporte_cotas)}));
export const aportesRelations = relations(s.aportes,({one,many})=>({obra:one(s.obras,{fields:[s.aportes.obra_id],references:[s.obras.id]}),cotas:many(s.aporte_cotas)}));
export const cotasRelations = relations(s.aporte_cotas,({one,many})=>({aporte:one(s.aportes,{fields:[s.aporte_cotas.aporte_id],references:[s.aportes.id]}),participacao:one(s.obra_socios,{fields:[s.aporte_cotas.obra_socio_id],references:[s.obra_socios.id]}),pagamentos:many(s.aporte_pagamentos)}));
export const aportePagamentosRelations = relations(s.aporte_pagamentos,({one})=>({cota:one(s.aporte_cotas,{fields:[s.aporte_pagamentos.cota_id],references:[s.aporte_cotas.id]})}));
export const ajustesRelations = relations(s.obra_ajustes_caixa,({one})=>({obra:one(s.obras,{fields:[s.obra_ajustes_caixa.obra_id],references:[s.obras.id]})}));
export const diarioRelations = relations(s.obra_diario,({one,many})=>({obra:one(s.obras,{fields:[s.obra_diario.obra_id],references:[s.obras.id]}),autor:one(s.usuarios,{fields:[s.obra_diario.autor_usuario_id],references:[s.usuarios.id]}),evento:one(s.auditoria_eventos,{fields:[s.obra_diario.auditoria_evento_id],references:[s.auditoria_eventos.id]}),documentos:many(s.documento_vinculos)}));
export const pendenciasRelations = relations(s.obra_pendencias,({one})=>({obra:one(s.obras,{fields:[s.obra_pendencias.obra_id],references:[s.obras.id]})}));
export const documentosRelations = relations(s.documentos,({one,many})=>({vinculos:many(s.documento_vinculos),anterior:one(s.documentos,{fields:[s.documentos.versao_anterior_id],references:[s.documentos.id],relationName:'documento_versao'})}));
export const vinculosRelations = relations(s.documento_vinculos,({one})=>({documento:one(s.documentos,{fields:[s.documento_vinculos.documento_id],references:[s.documentos.id]}),despesa:one(s.despesas,{fields:[s.documento_vinculos.despesa_id],references:[s.despesas.id]}),pagamento:one(s.pagamentos_despesa,{fields:[s.documento_vinculos.pagamento_despesa_id],references:[s.pagamentos_despesa.id]}),diario:one(s.obra_diario,{fields:[s.documento_vinculos.diario_id],references:[s.obra_diario.id]})}));
export const documentoImovelVinculosRelations = relations(s.documento_imovel_vinculos,({one})=>({documento:one(s.documentos,{fields:[s.documento_imovel_vinculos.documento_id],references:[s.documentos.id]}),imovel:one(s.imoveis,{fields:[s.documento_imovel_vinculos.imovel_id],references:[s.imoveis.id]})}));
